name: linux

on:
  push:
  pull_request:
    paths:
      - 'include/**'
      - 'sources/**'
      - 'tests/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Release]

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_TESTS=ON $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: |
          threads=`nproc`
          cmake --build . --config ${{matrix.build_type}} --parallel $threads

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest -C ${{matrix.build_type}}
        env:
          CTEST_OUTPUT_ON_FAILURE: True
